language: node_js
node_js:
  - "6"
  - "8"
  - "10"
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
install:
  - CC=gcc-4.9 CXX=g++-4.9 npm install
